# Generated by Django 5.1.1 on 2024-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game2', '0002_alter_levelprize_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlevel',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
