# Generated by Django 5.1.1 on 2024-10-03 19:54

import django.db.models.deletion
import django.utils.timezone
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, unique=True)),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_joined_today', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('boost', models.ForeignKey(default=game.models.Player.get_default_boost, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='boost', to='game.boost')),
            ],
        ),
    ]
